# Generated by Django 6.0.6 on 2026-07-25 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='jobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=230)),
                ('jobDescription', models.CharField(help_text='Enter the Job Description', max_length=300)),
                ('experienceLevel', models.CharField(max_length=5)),
                ('companyName', models.CharField(help_text='Enter Company Name', max_length=200)),
                ('companyAddress', models.CharField(help_text='Enter the Address', max_length=300)),
                ('salaryPackage', models.CharField(help_text='Enter the Salary Package', max_length=10)),
                ('supportingDocuments', models.FileField(blank=True, null=True, upload_to='supportDocs/')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiredDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('empType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_type', to='jobPosting.employeetype')),
                ('jobAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('jobStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_status', to='jobPosting.jobstatus')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
