# Generated by Django 6.0.6 on 2026-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='experienceLevel',
            field=models.CharField(max_length=15),
        ),
    ]
