# Generated by Django 6.0.6 on 2026-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPosting', '0002_alter_jobposting_experiencelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='employeeType',
            field=models.CharField(choices=[('full-time', 'FullTime'), ('part-time', 'PartTime'), ('contract', 'Contract Based'), ('intern', 'Internship')], default='', help_text='Enter the Employee Type', max_length=100),
            preserve_default=False,
        ),
    ]
