# Generated by Django 6.0.6 on 2026-07-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPosting', '0003_employeetype_employeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='job_status',
            field=models.CharField(choices=[('is-active', 'Active'), ('close', 'Closed'), ('under-review', 'UnderReview'), ('draft', 'Draft')], default='', help_text='Enter the Job Status', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='jobStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobStatus', to='jobPosting.jobstatus'),
        ),
    ]
