# Generated by Django 6.0.6 on 2026-07-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPosting', '0004_jobstatus_job_status_alter_jobposting_jobstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='jobStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='jobPosting.jobstatus'),
        ),
    ]
