# Generated by Django 6.0.7 on 2026-07-29 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPosting', '0006_jobapply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='trackJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(help_text='Enter the Status of the Applied Job', max_length=100)),
                ('jobApplied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackJobs', to='jobPosting.jobapply')),
                ('jobAppliedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobUserss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
