# Generated by Django 6.0.6 on 2026-07-14 07:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the Event Title', max_length=100)),
                ('place', models.CharField(help_text="Enter the Event's Place:", max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Enter your First Name:', max_length=100)),
                ('lastName', models.CharField(help_text='Enter your Last Name:', max_length=100)),
                ('address', models.CharField(help_text='Enter your Address', max_length=100)),
                ('phoneNumber', models.CharField(help_text='Enter Contact Number', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuthUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatingCapacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('userTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', to='eventHandle.eventregister')),
                ('registeredUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='eventHandle.userregister')),
            ],
        ),
    ]
