# Generated by Django 6.0.6 on 2026-07-18 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='totalCapacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
